@baseUrl = http://localhost:5010

### Criar nota fiscal
POST {{baseUrl}}/api/notas-fiscais

### Listar notas fiscais
GET {{baseUrl}}/api/notas-fiscais

### Adicionar item
POST {{baseUrl}}/api/notas-fiscais/731138d2-293b-470f-9a22-fd618a775744/itens
Content-Type: application/json

{
  "produtoId": "d07af155-934c-439b-a60c-657c8a7a72aa",
  "descricaoProduto": "Caneta esferográfica",
  "quantidade": 1
}

### Imprimir nota fiscal
POST {{baseUrl}}/api/notas-fiscais/731138d2-293b-470f-9a22-fd618a775744/imprimir