// <auto-generated />
using System;
using Faturamento.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Faturamento.Api.Migrations
{
    [DbContext(typeof(FaturamentoDbContext))]
    partial class FaturamentoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Faturamento.Api.Domain.NotaFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("NotasFiscais");
                });

            modelBuilder.Entity("Faturamento.Api.Domain.NotaFiscal", b =>
                {
                    b.OwnsMany("Faturamento.Api.Domain.ItemNotaFiscal", "Itens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DescricaoProduto")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("NotaFiscalId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ProdutoId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("NotaFiscalId");

                            b1.ToTable("ItemNotaFiscal");

                            b1.WithOwner()
                                .HasForeignKey("NotaFiscalId");
                        });

                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
